version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: keinos/sqlite3:latest
    volumes:
      - ./data:/data
    networks:  # Indentation corrigée ici
      - my_network

networks:
  my_network:
    driver: bridge